### PR TITLE
Streamline the header include see https://github.com/orocos-toolchain/orogen/pull/15 for details

### PR DESCRIPTION
**Pull request by goldhoorn**

### CODE REVIEW

**Comment by goldhoorn** [comment]
@jmachowinski maintainer? ping

**Comment by jmachowinski** [comment]
I'm author, but not maintainer....
Thought you maintain this package...

**Comment by goldhoorn** [comment]
don't know i don't care in general right now. However i merge...

**Comment by goldhoorn** [comment]
Feel free to create a PR on the package set and call remove_from_default, and add please a comment that this is depricated and not longer maintained...

**Pull request merged**
